import React from 'react';
import RoboGif from "./../../../../assets/images/robogif.gif"
import {Link} from "react-router-dom";
const InfoV2:React.FC = () => {
    return (
        <div id={"overview"} className="h-screen snap-center flex flex-col items-center justify-center">
            <div className="h-full flex  flex-col xl:flex-row w-full justify-center items-center xl:max-w-7xl xl:justify-between gap-y-5 xl:gap-7">
                <div className="flex-1 xl:flex-[2] relative  w-full h-full p-10 xl:p-0">
                    <img
                        src={RoboGif}
                        alt=""
                        draggable={false}
                        onContextMenu={(e)=>e.preventDefault()}
                        className="xl:absolute top-0 left-0 right-0 bottom-0 m-auto  w-full h-full object-contain xl:w-auto xl:h-auto "
                    />
                </div>
                <div className="flex-1 xl:flex-[3] items-center xl:items-start xl:flex-2 flex flex-col justify-center gap-6">
                    <h1 className="text-4xl xl:text-7xl text-center xl:text-start text-base-content font-bold"> Path Following Robot </h1>
                    <div className="flex items-center gap-3">
                        <span className="w-8 h-2 rounded-full bg-base-content/50"/>
                        <h4 className="text-lg xl:text-2xl text-primary font-bold">Path Planning with A* Algorithm</h4>
                    </div>
                    <p className="text-sm text-base-content/90 xl:text-xl text-center xl:text-start">
                        A* is an algorithm that searches for the shortest path between the robot’s current location and a target destination.
                        The robot uses the map generated by SLAM to identify obstacles and calculate a safe, efficient path to its goal.
                    </p>
                    <Link to="/visualizer" className="text-2xl xl:text-5xl font-bold cursor-pointer  text-stroke"  data-text={"Try It Know"}>Try It Know</Link>

                </div>

            </div>
        </div>
    );
};

export default InfoV2;
